version: 2

seeds:
  - name: customers
  - name: orders
  - name: products

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
          - unique

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
